### Data Science

- A field of science that study the data, anlayse the data and performs various steps on the data to get valuable insights.
    - ex: google, google maps, uber, amazom, flipcart ..etc
- It has some powerful libraries or packages
    - NumPy,Pandas and Matplotlib
        - NumPy
            - Scientific caluculation
        - Pandas
            - Data Manupulation, analysis and cleaning
        - Matplotlib
            - Visulization
            
    

## NumPy

- It means Numerical Python
- It is one of the data science packages
- Here we dealing with array kind of data
- The main purpose of this package is to do scientific caluculations
    - Logarthmic, Liner alzebra, FT, Trig, exp ...
- smaller memory consumption
- better runtime


In [ ]:
## idle

-- pip install numpy

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.array([2,6,4,5])
a

array([2, 6, 4, 5])

In [8]:
type(a)
print(a.ndim)

1


In [5]:
b = np.array([[3,4,5],[7,6,5],[8,3,9]])
b

array([[3, 4, 5],
       [7, 6, 5],
       [8, 3, 9]])

In [13]:
## predefined functions

print(type(b))
print(b.ndim)
print(a.ndim)
print(b.shape)
print(a.shape)
print(b.size)
np.__version__

<class 'numpy.ndarray'>
2
1
(3, 3)
(4,)
9


'1.18.5'

## range

In [17]:
## range(start,end,step/updation/inc/dec)

ar = np.array(range(5))
print(ar)
print('.......................')
ar1 = np.array(range(1,10))
print(ar1)
print('........................')
ar2 = np.array(range(1,20,2))
print(ar2)
print(type(ar2))


[0 1 2 3 4]
.......................
[1 2 3 4 5 6 7 8 9]
........................
[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>


## arange()

In [22]:
x = np.arange(5)
print(x)
y = np.arange(1,30)
print(y)
z = np.arange(1,15,2)
print(z)

[0 1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[ 1  3  5  7  9 11 13]


## reshape()

In [23]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
a1 = np.arange(25)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
b1 = np.arange(12).reshape(-1,4)
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b2 = np.arange(12).reshape(6,-1)
b2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
o = np.ones((7,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
o = np.ones((7,4), dtype = int)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
z = np.zeros((3,5), dtype = int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
s = np.full((4,5),8)
s

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [32]:
s = np.full((4,5),8.7)
s

array([[8.7, 8.7, 8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7, 8.7, 8.7]])

In [34]:
e = np.eye(6)
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
e = np.eye(6,dtype = int)
e

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [36]:
d = np.diag(e)

In [37]:
d

array([1, 1, 1, 1, 1, 1])

In [38]:
n = np.arange(9).reshape(3,3)
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
r = np.diag(n)

r

## random()

In [41]:
a = np.random.random((6))
a

array([0.98318748, 0.08247519, 0.02142207, 0.82275818, 0.11079718,
       0.07912636])

In [42]:
t = np.random.random((6)).reshape(2,3)
t

array([[0.31919796, 0.11898325, 0.91283059],
       [0.43568598, 0.27392186, 0.11114233]])

In [43]:
f = np.random.rand(5,2)
f

array([[0.36197836, 0.71277399],
       [0.78164619, 0.80003773],
       [0.49985568, 0.48340347],
       [0.97198222, 0.01463881],
       [0.53833498, 0.48405344]])

In [44]:
f1 = np.random.randn(2,3)
f1

array([[ 0.69896816,  1.19716359,  0.66134065],
       [-1.52017663, -0.62767496,  0.53376595]])

In [45]:
a = np.random.randint(1,30,(10,3))
a

array([[ 4, 10, 12],
       [28, 28, 11],
       [ 2, 11,  9],
       [18, 27,  8],
       [13, 14,  3],
       [ 6,  2,  8],
       [ 6,  4, 19],
       [ 9, 15, 17],
       [ 1,  4, 10],
       [16, 14,  1]])

In [46]:
a[1:5]

array([[28, 28, 11],
       [ 2, 11,  9],
       [18, 27,  8],
       [13, 14,  3]])

In [47]:
a[:]

array([[ 4, 10, 12],
       [28, 28, 11],
       [ 2, 11,  9],
       [18, 27,  8],
       [13, 14,  3],
       [ 6,  2,  8],
       [ 6,  4, 19],
       [ 9, 15, 17],
       [ 1,  4, 10],
       [16, 14,  1]])

In [48]:
a[2:,:3]

array([[ 2, 11,  9],
       [18, 27,  8],
       [13, 14,  3],
       [ 6,  2,  8],
       [ 6,  4, 19],
       [ 9, 15, 17],
       [ 1,  4, 10],
       [16, 14,  1]])

In [49]:
a

array([[ 4, 10, 12],
       [28, 28, 11],
       [ 2, 11,  9],
       [18, 27,  8],
       [13, 14,  3],
       [ 6,  2,  8],
       [ 6,  4, 19],
       [ 9, 15, 17],
       [ 1,  4, 10],
       [16, 14,  1]])

In [50]:
print(a>5)

[[False  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True False]
 [ True False  True]
 [ True False  True]
 [ True  True  True]
 [False False  True]
 [ True  True False]]


In [51]:
a[a>5]

array([10, 12, 28, 28, 11, 11,  9, 18, 27,  8, 13, 14,  6,  8,  6, 19,  9,
       15, 17, 10, 16, 14])

In [52]:
a[a>5].sum()

309